sonar.projectKey=python-sonarqube-demo
sonar.projectName=Python SonarQube Demo
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=test_*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=.pytest_cache/**,coverage.xml
